### ISSUE TITLE
Windows.h not found (on case-sensitive OS)

### ISSUE THREAD

**Issue by olivier-omnirobotic** [aiekick/ImGuiFileDialog#115] opened 2022-12-20 05:12 UTC
Suggestion for a very quick fix to support case-sensitive OS. 
in `ImGuiFileDialog.cpp` at line 60, `#include <Windows.h>` should be `#include <windows.h>` (lowercase W). 

This makes it work properly on case-sensitive OS (for instance in Linux when compiling with MinGW) without breaking it for a normal windows machine. 

Other than that, cross-compiling from Linux to Windows with MinGW works fine with that fix alone.

**Comment by aiekick** [comment] 2022-12-21 07:13
Hello,

Thanks for your feebdack.

In my mind on windows other compiler than msvc dont make ImGuiGileDialog work with unicode ( like other imgui based soft, like i found this answer on stackoverflow confirmed by my tests)

And im surprised if this fix can work, because if the header was not the good one, why not compiler errors ?

But ok , i will check that

**Comment by aiekick** [comment] 2022-12-22 14:18
your fix is not working on my side

**Comment by olivier-omnirobotic** [comment] 2022-12-23 03:29
What is not working? are you referring to it breaking something on windows, or to the other unicode issue?
I don't have this unicode issue on my end... 
I have opened this issue only for the wrong include file name which should be all lowercase. 
So either way it should be changed to non-capitalized "windows.h" since that is the actual filename and this should not break anything else, it will just fix something. 
Now the unicode issue is totally separate and should be dealt with as another separate issue. and I cannot help with it since I am not experiencing it.

**Comment by olivier-omnirobotic** [comment] 2022-12-23 03:39
On my side, I am cross-compiling from a Linux machine (ArchLinux) using MinGW targetting a 64-bit Windows architecture. 
It compiles without error if I simply change `include <Windows.h>` to `include <windows.h>` and then it also runs fine on a windows machine without errors (although I haven't tested with filepaths containing weird characters). 
I also have not tried compiling it directly on a windows machine using MinGW... if this causes compiling issues or there are runtime issues regarding unicode characters in filepaths, that's a totally different problem and should be treated as a different issue.

**Comment by aiekick** [comment] 2022-12-23 10:36
ok sorry, not understood the meaning of your issue :)

**Comment by aiekick** [comment] 2022-12-23 10:45
fixed in c98abd5ba61ac3a1d501cdec2f870cbe27f80b27

**Closed by aiekick** 2022-12-23 10:45 UTC
Labels: unicode

**Comment by olivier-omnirobotic** [comment] 2023-01-10 01:57
Sorry, but the fix was not included in your latest commit, only a typo in the README was fixed.

**Comment by aiekick** [comment] 2023-01-11 18:30
ok, was fixed in af4800e85a79154c8c08cf28d4cfee82bdc0cd03
