### ISSUE TITLE
Only for Windows.

### ISSUE THREAD

**Issue by AlastairGrowcott** [aiekick/ImGuiFileDialog#2] opened 2019-08-10 08:27 UTC
This code is 100% only for Windows. Apart from the many many Windows specific bits, like using the \ character as a path separator, Microsoft have once again horribly bastardised a standard Posix function. The whole "dirent" family of functions are clearly very very different on Windows to any Posix system.

Apart from that, thankyou for taking the time to write this. It will be much quicker for me to fix this than write my own from scratch.

**Comment by aiekick** [comment] 2019-08-10 15:23
haha, yes, i dont know linux on the dev side :) 

by the way there is some bugs about the path decomposition some times,

thanks :)

**Comment by AlastairGrowcott** [comment] 2019-08-12 18:08
Path decomposition is all different for Linux anyway. I've modded for Linux and it is (mostly) working well. The initial dialog size is too small to show the buttons.

I made my changes without much consideration for Windows. Would you be interested in me pushing my changes as a diff so you can see them and we can try to get them working for both platforms? I don't have a handy Windows machine to test on, so it would need both of us.

Also, as I was modding for myself I changed naming conventions a bit, so that will make things a bit more awkward.

**Comment by aiekick** [comment] 2019-08-13 07:44
im interested yes. thank you. it can be cool to produce some crosse platform code :)

**Comment by aiekick** [comment] 2019-09-18 15:21
im curious is there an ide you are using with linux ? what is your toolchain ?

**Comment by AlastairGrowcott** [comment] 2019-09-19 06:44
I don't use an IDE, but I understand that Eclipse is very popular. Like almost everyone I use GCC as my compiler. There is also clang, but as that uses GCC anyway...

At work on Windows I usually use GCC too. There is a thing called MSys2 that gives a Posix-like environment (bash shell etc.) and includes cross compilers (MinGW GCC) and so on. I only use Visual Studio when there is no other choice. Frankly the Win32 API is utter crap. Just at the moment I am finding that the Microsoft version of recvfrom() does not perform as per the documentation.

**Comment by AlastairGrowcott** [comment] 2019-09-19 06:48
By the way I found some bugs in the dialogue the other day. One was because I wasn't using it the way it was intended but others were genuine bugs that I think I introduced by not understanding how it was meant to work. I will push some fixes when I have a chance, but it is a bit tricky because of the way I have renamed stuff to try and keep the naming consistent with other IMGUI APIs and file names.

Also, IMGUI is a C API but your dialogue is a C++ API. If you modified it to be a proper C API and work in a proper IMGUI way, you could probably get your code incorporated into the main IMGUI repository.

**Comment by aiekick** [comment] 2019-09-19 14:07
i understand by the way this repo was just a demo of what we can do.
for my use case this class is not more the same, and i have corrected many bugs and add features.
at some point in the future i will release my soft on linux, and at some point also will put it in open source. so i get some knowledge about this. so you can do what you want with this class.
its easier for me to use this as a singleton, but yes if we can code this in a IMGUI way it will be better for the community maybe

**Comment by timbeaudet** [comment] 2019-09-23 13:20
With this being only for Windows, why not just use the built in OpenFileDialog for windows, I went into this expecting it was cross-platform, shame on me? since it was ImGui display, and the troubles of using a 'dirent' like replacement...

I am in need of this solution on Linux, any chance of it it happening soon?

**Comment by aiekick** [comment] 2019-09-23 14:24
it was only an examples of what we can do with imgui for filedialog.
if you need a linux version you can use the version of @AlastairGrowcott or others,(there is many other filedialog system created with imgui).

i not use OpenFileDialog  for windows, because i need to display a settings pane in the dialog for some ext or features, so it was needed to create this file dialog. by the way my version is now completly different than this repo. so you can use that and modifiy it for your project, and just see what we can do.

if i publish my version it will breack this one, and i need to publish some parts of my framework. this is not what i want currently

**Comment by AlastairGrowcott** [comment] 2019-09-24 06:45
Life is a bit busy at the moment, but I will update my branch with the various fixes I haven't put across yet. It isn't completely cross-platform as I think it breaks Windows.

I think I might completely update my branch by removing all the files that are normally provided by ImGUI anyway. And if I wasn't so busy I would convert the C++ class to be a C API along the lines of the rest of ImGUI. But the game I am writing takes priority really.

**Comment by AlastairGrowcott** [comment] 2019-09-30 17:36
I found a bit of spare time. My fork now has only the additional files and more of an ImGUI style API. Still could be improved a lot more but is ok for now.

Works well on Linux, not sure about Windows.

**Comment by aiekick** [comment] 2019-09-30 23:39
i will upload a new code for this repo (tested on linux and windows) but he will break the current working.
i merged some fo your modifications with my new code im using for [NoodlesPlate](https://github.com/aiekick/NoodlesPlate) since many month ago now

**Comment by aiekick** [comment] 2019-09-30 23:40
the new code permit the use of custom pane via function pointer with dialog

**Comment by aiekick** [comment] 2019-12-10 00:58
i have created a second branch with the new version of ImGuiFileDialog.

fully cross platform (tested on the WIn/Linux/MacOs)
https://github.com/aiekick/ImGuiFileDialog/tree/ImGuiFileDialog_V2

the behavior of this one is a bit different of the first version. i use this new one in all my projects.

since its completly different is this a good idea to merge in the master branch ?

**Closed** 2019-12-11 12:32 UTC

**Comment by dandingol03** [comment] 2021-09-19 04:57
doesn't work on mac, i try to use this plugin in filament, but i can't make the file dialog show

**Comment by aiekick** [comment] 2021-09-19 09:22
you know this issue was fixed a while ?
did you test the sample app on mac by ex before say its not working ?
maybe the problem is not my "plugin" but you, who dont undersstand how this is working.
and with the "big effort" you have with your message to help me, its a time loss.
i not have time to help guys who not what to take some effort to help.
so i wil; say, if its not wroking for you. with this "big effort" you have, ok tis not working, so  dont use it. 
bye !
